# PluginVersions
#
# See http://wiki.bukkit.org/Plugin_YAML for a complete list of requirements and options.

name: PluginVersions
version: ${project.version}
api-version: 1.21.11
main: com.straight8.rambeau.bukkit.PluginVersionsBukkit
description: List installed plugins and versions alphabetically
authors: [ mart-r, GabrielHD150, SlimeDog ]

commands:
  pluginversions:
    description: Commands for PluginVersions
    usage: <command> list | <command> reload
    aliases: [ pv ]
  pluginversions list:
    description: List loaded plugins and versions
    usage: <command> [page]
  pluginversions reload:
    description: Reload configuration file
    usage: <command>

permissions:
  pluginversions.*:
    description: Allows access to all PluginVersions commands
    children:
      pluginversions.list: true
      pluginversions.reload: true
  pluginversions.list:
    description: Allows you to retrieve PluginVersions listing
    default: op
  pluginversions.reload:
    description: Allows you to reload PluginVersions configuration
    default: op
    
